Increment 17
ITD27M01/go-metrics-service pull request #24
Opened 2022-05-30 12:27 UTC by ITD27M01

2022-06-05 22:40 UTC, Barugoo commented on internal/server/handlers_example_test.go
> +}
Круто, что ты добавил в example тесты, но этот функционал больше нужен для юнит-тестов, а не для интеграционных. Здесь по заданию ожидается что-то вроде
![изображение](https://user-images.githubusercontent.com/27661724/172073584-331e58b2-1357-49d6-a585-6e651e977662.png)

https://medium.com/@danielphan/try-things-testing-part-1-a734215b25fa

2022-06-05 22:43 UTC, Barugoo commented on internal/models/metrics/metrics.go
>  	ID    string   `json:"id"`              // Имя метрики
Давай перепишим все комменты на английский

2022-06-05 22:44 UTC, Barugoo requested changes
Комменты гуд, не вижу бенчмарков. Как идея: можно сделать две реализации хранилки метрик на сервере - через массив/линкед-лист и через мапку и сравнить их производительность в бенчмарках на разных операциях. Бенчмарки и разницу профилей сохранить

2022-06-12 14:27 UTC, ITD27M01 commented on internal/server/handlers_example_test.go
> +}
В уроке рассказано именно про тесты, поэтому и задание сделал так.

2022-06-13 12:16 UTC, rktkov approved these changes

2022-06-23 16:55 UTC, merged